### PR TITLE
Speakers UI is a tad nicer

### PR DESCRIPTION
**Pull request by mdarby**
columbus elixir 2018-02-20 12-06-41

### CODE REVIEW

**Comment by ghost** [comment]
@mdarby How do you plan on managing the monthly speakers?  Not sure how this works on the .rb equivalent, is it enough just to edit this page every month?

**Comment by mdarby** [comment]
Great question; the CRB site has a "hidden" REST endpoint where we can POST new speakers. 
Right now this sucker doesn't even have a DB... :)

**Comment by ghost** [comment]
On this pr, I do have some questions.  

Do we need that anchor tag wrapping the content  (maybe we'd need a url to the person's website if they have one)? 

The img tag is missing an alt, I think if nothing else there should be an alt there that says "Speaker Image".

As for the actual details block, admittedly this is super nitpicky, but it might not be a bad idea just to build out the typography styles in a way that you can just drop h2/h3, p, i, whatever in those blocks without needing to explicitly specify them with redundant classes across the site.  At least that's how I've done it in the past, but I'm not sure that it's the right approach?

**Comment by mdarby** [comment]
@mkolich yep, each speaker is wrapped in a (currently empty) `a` tag for the speaker's link.
I'll add the `alt`; the H2/H3 are overwritten by TypeKit. If I update the tags then the text looks odd...

**Comment by ghost** [comment]
Okay, I opened an issue to tidy up the scss so maybe we can address the headings there.

**Review by ghost — APPROVED** [review]

**Pull request merged**
