### PR TITLE
Adds Patreon link

### PR DESCRIPTION
**Pull request by mdarby**
columbus elixir 2018-02-20 12-29-49

### CODE REVIEW

**Comment by croz1007** [comment]
I know this is the patreon we set up at your house yesterday for MP. Do we need to have different ones? Elixir group, YouTube channel, etc. The reason I ask is that typically people will become a patron for your whatever because they get special things like access to a private slack chat, extra content others may not get, things like that. Just wondering your thoughts on this.

I know for the Elixir group it is good because people can help fund the group and I agree that people should want to do that.

**Comment by mdarby** [comment]
That crossed my mind too -- could you set one up for the group and add it to 1P?

**Comment by croz1007** [comment]
Set one up for the Elixir group? Will do.

**Comment by croz1007** [comment]
I am wondering if we should have the link for this in a paragraph too just to explain what is is and why we set it up. More than just a link to sit there w/o explanation for a "Send me your money" <Suicidal Tendencies> vibe.

**Pull request merged**
